package db;

public enum Action {
	LOGIN, INSERT, UPDATE, DELETE, GET, NOTIFICATION,GET_ALL, GET_ALL_APPOINTMENTS, GET_ALL_APPOINTMENT_USERS,
	SUCCESS, DISCONNECT, GET_ALL_USERS, GET_NOTIFICATION, SET_STATUS_ATTENDING, SET_STATUS_NOT_ATTENDING, MASSIVE_FAILURE, GET_ALL_USERS_ALL_APPOINTMENTS, GET_MEETINGPOINT;
}
