package db;

public enum Action {
	LOGIN, INSERT, UPDATE, DELETE, GET, NOTIFICATION,GET_ALL, GET_ALL_APPOINTMENTS,
	SUCCESS, MASIVE_FAILURE, DISCONNECT, GET_ALL_USERS, SET_STATUS_ATTENDING, SET_STATUS_NOT_ATTENDING;
}
